site/src/Entity/AgenceA.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\AgenceARepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Entity(repositoryClass=AgenceARepository::class)
 */
class AgenceA
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     * 
     * @Groups("agenceA:read")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * 
     * @Groups({"agenceA:read", "agenceA:write"})
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * 
     * @Groups({"agenceA:read", "agenceA:write"})
     */
    private $prenom;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * 
     * @Groups({"agenceA:read", "agenceA:write"})
     */
    private $Entreprise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * 
     * @Groups({"agenceA:read", "agenceA:write"})
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=50, nullable=true)
     * 
     * @Groups({"agenceA:read", "agenceA:write"})
     */
    private $tel;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(?string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(?string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getEntreprise(): ?string
    {
        return $this->Entreprise;
    }

    public function setEntreprise(?string $Entreprise): self
    {
        $this->Entreprise = $Entreprise;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->tel;
    }

    public function setTel(?string $tel): self
    {
        $this->tel = $tel;

        return $this;
    }
}

site/src/Controller/AgenceAController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\AgenceA;

class AgenceAController extends AbstractController
{
    /**
    * @Route("/agenceA", name="agenceA")
    */
   public function index(): Response
   {
        // Méthode findBy qui permet de récupérer tous les données Agence A
        $agenceA = $this->getDoctrine()->getRepository(AgenceA::class)->findBy([], ['id' => 'asc']);

       // Nous générons la vue de la page agenceA
       return $this->render('agence_a/index.html.twig', [
           'agenceA' => $agenceA,
       ]);
   }
}

site/templates/agence_a/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Agence A{% endblock %}

{% block body %}
    <h1>Agence A</h1>
        <div class="container">
            <div class="row">
                {% for agenceA in agenceA %}
                    <div class="col-12 col-md-6">
                            <div class="card mb-4">
                                <div class="card-header">
                                    <img src="https://picsum.photos/300/200" class="Hero-new"/>
                                    <p><span class="bold"> Nom : </span>{{ agenceA.nom }}</p>
                                    <p><span class="bold">Prénom : </span>{{ agenceA.prenom }}</p>
                                    <p><span class="bold">Entreprise : </span>{{ agenceA.entreprise }}</p>
                                    <p><span class="bold">Email : </span>{{ agenceA.email }}</p>
                                    <p><span class="bold">Tel : </span>{{ agenceA.tel }}</p>
                                </div>
                            </div>
                    </div>
                {% endfor %}
            </div>
        </div>
{% endblock %}